#!/bin/bash
root=`dirname $0`
cd "$root"
root=`pwd`
mkdir -p "$root/share/pcdev"
cd "$root/share"
echo INF: Checking Aztec 3.4 tools ...
if [ ! -d aztec34/bin -o ! -f emu/cpm86.exe ];then
    wget "https://www.aztecmuseum.ca/az8634b.zip"
    unzip -L az8634b.zip
    mkdir -p "$root/share/aztec34"
    mkdir -p "$root/share/emu"
    mkdir -p "$root/share/aztec42/src"
    cp -R az8634b/bin aztec34
    cp -R az8634b/lib aztec34
    cp -R az8634b/emu/cpm.exe emu/cpm86.exe
    cp -R az8634b/obj/* aztec34/lib
    cp -R az8634b/src aztec34
    cp -R az8634b/src/dos11.arc aztec42/src
    cp -R az8634b/src/cpm86.arc aztec42/src
    cp -R az8634b/include aztec34
    rm -rf az8634b.zip az8634b
fi
echo INF: Checking Aztec 4.2 tools ...
cd "$root/share"
if [ ! -d aztec42/bin ];then
    wget "https://www.aztecmuseum.ca/AztecC86.zip"
    unzip -L AztecC86.zip
    mkdir -p "$root/share/aztec42"
    cp -R aztecc86/bin aztec42
    cp -R aztecc86/lib aztec42
    cp -R aztecc86/obj aztec42
    cp -R aztecc86/arc/* aztec42/src
    cp -R aztecc86/include aztec42
    rm -rf AztecC86.zip aztecc86
fi
echo INF: Checking CP/M DR tools ...
cd "$root/share"
if [ ! -f cpm/asm86.com -o ! -f cpm/gencmd.com ]; then
    rm -rf "$root/share/temp-tools"
    mkdir -p "$root/share/cpm"
    mkdir -p "$root/share/temp-tools"
    cd "$root/share/temp-tools"
    wget "http://www.cpm.z80.de/download/mpm862sr.zip"
    unzip -L mpm862sr.zip
    cp 03/a86.cpm ../cpm/asm86.com
    cp 03/gencmd.cpm ../cpm/gencmd.com
    chmod 644 ../cpm/*.*
    rm -rf "$root/share/temp-tools"
fi
echo INF: Checking DOS DR tools ...
cd "$root/share"
if [ ! -f pcdev/linkcmd.exe -o ! -f pcdev/rasm86.exe -o ! -f pcdev/linkexe.exe \
   -o ! -f pcdev/lib86.exe ]; then
    rm -rf "$root/share/temp-tools"
    mkdir -p "$root/share/pcdev"
    mkdir -p "$root/share/temp-tools"
    cd "$root/share/temp-tools"
    wget "http://www.cpm.z80.de/download/tools86.zip"
    unzip -L tools86.zip
    unzip -L dos86pr2.zip
    cp linkcmd.exe rasm86.exe ../pcdev
    cp linkexe.exe ../pcdev
    cp lib86.exe ../pcdev
    chmod 644 ../pcdev/*.*
    rm -rf "$root/share/temp-tools"
fi
echo INF: Checking CB86  ...
cd "$root/share"
if [ ! -f cb86cpm/cb86.exe -o ! -f cb86dos/cb86.exe \
    -o ! -f cb86cpm/cb86.l86 -o ! -f cb86dos/cb86.l86 ]; then
    rm -rf "$root/share/temp-tools"
    mkdir -p "$root/share/cb86cpm"
    mkdir -p "$root/share/cb86dos"
    mkdir -p "$root/share/temp-tools"
    cd "$root/share/temp-tools"
    wget "http://www.cpm.z80.de/download/cbasic86.zip"
    unzip -L cbasic86.zip
    cp cb86.l86 ../cb86cpm
    cp ../pcdev/linkcmd.exe ../cb86cpm/link86.exe
    cp ../pcdev/lib86.exe ../cb86cpm/lib86.exe
    cp ../pcdev/rasm86.exe ../cb86cpm/rasm86.exe
    rm ../temp-tools/*.*
    wget "http://www.cpm.z80.de/download/cb86toys.zip"
    unzip -L cb86toys.zip
    cp cb86.exe ../cb86dos
    cp cb86.or1 ../cb86dos
    cp cb86.or2 ../cb86dos
    cp cb86.or3 ../cb86dos
    cp cb86.l86 ../cb86dos
    cp ../cb86dos/cb86.exe ../cb86cpm/cb86.exe
    cp ../cb86dos/cb86.or1 ../cb86cpm/cb86.or1
    cp ../cb86dos/cb86.or2 ../cb86cpm/cb86.or2
    cp ../cb86dos/cb86.or3 ../cb86cpm/cb86.or3
    cp ../pcdev/linkexe.exe ../cb86dos/link86.exe
    cp ../pcdev/lib86.exe ../cb86dos/lib86.exe
    cp ../pcdev/rasm86.exe ../cb86dos/rasm86.exe
    chmod 644 ../cb86cpm/*.*
    chmod 644 ../cb86dos/*.*
    rm -rf "$root/share/temp-tools"
fi
echo INF: Checking Microsoft tools ...
if [ ! -f pcdev/masm.exe -o ! -f pcdev/exe2bin.exe -o ! -f pcdev/link.exe ]; then
    cd "$root/share"
    mkdir -p "$root/share/pcdev"
    cp ../sources/microsoft/*.exe pcdev
    chmod 644 pcdev/*.*
fi
if [ ! -f pcdev/asm.com -o ! -f pcdev/hex2bin.com ]; then
    cd "$root/share"
    mkdir -p "$root/share/pcdev"
    cp "$root/sources/microsoft"/*.com pcdev
    chmod 644 pcdev/*.*
fi
echo INF: Checking CMD tools ...
if [ ! -f pcdev/cmdnfo.com -o ! -f pcdev/bin2com.com ]; then
    cd "$root/share"
    mkdir -p "$root/share/pcdev"
    cp "$root/sources/cmdtools"/*.com pcdev
fi
echo INF: Checking TNYLPO ...
cd "$root"
if [ ! -d tnylpo ];then
    git clone "https://gitlab.com/gbrein/tnylpo.git"
fi
if [ ! -f bin/tnylpo ];then
    (cd tnylpo;make -j4;cp tnylpo ../bin)
fi
echo INF: Checking NASM ...
cd "$root"
if [ ! -d nasm ];then
    wget "https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.gz"
    tar zxf nasm-2.15.05.tar.gz 
    mv nasm-2.15.05 nasm
    rm -f nasm-2.15.05.tar.gz
fi
if [ ! -f bin/nasm ];then
    (cd nasm;./configure;make -j4;cp nasm ../bin)
fi
echo INF: Checking EMU2 ...
cd "$root"
if [ ! -d emu2 ];then
    git clone "https://github.com/dmsc/emu2"
fi
if [ ! -f "$root/bin/emu2" ];then
    (cd "$root/emu2";make -j4;cp "$root/emu2/emu2" "$root/bin")
fi
find "$root/share" -type d -exec chmod 755 {} \;
find "$root/share" -type f -exec chmod 644 {} \;
echo INF: Unpacking Aztec 4.2 ...
cd "$root"
if [ ! -f "$root/share/aztec42/unpacked" ];then
    (cd "$root/share/aztec42"; "$root/sources/aztec42-patch/unpack")
fi
echo INF: Patching Aztec 4.2 ...
cd "$root"
if [ ! -f "$root/share/aztec42/patched" ];then
    (cd "$root/share/aztec42"; tar zxvf "$root/sources/aztec42-patch/patches.tar.gz")
    (cd "$root/share/aztec42"; "$root/sources/aztec42-patch/apply_patches")
fi
echo INF: Building Aztec 4.2 ...
cd "$root"
if [ ! -f "$root/share/aztec42/built" ];then
    chmod 755 "$root/share/aztec42/src/build"
    (cd "$root/share/aztec42/src"; PATH="$root/bin":$PATH ./build)
	rm -rf "$root/share/aztec42/lib"/*
	mv "$root/share/aztec42/src/libs"/* "$root/share/aztec42/lib"
    touch "$root/share/aztec42/built"
fi
exit 0
