#!/bin/sh
if [ ! -d src ];then
    echo "ERR: Please execute from Aztec C root" >&2
    exit 0;
fi
cd src
for i in *.arc;do 
    r=`echo $i|sed -e 's/.arc$//g'`
    mkdir -p $r
    cp $i $r/$i
    (cd $r;../../../../bin/emu2 ../../bin/arcv.com $i; rm $i) 
done
mv build/* .
mv s screen
mv g graphics
rmdir build
mv cpm86/c86.bld .
mv misc/misc.bld .
for i in *.bat *.bld */*.c */*.asm makefile */makefile;do 
	dos2unix $i
    if [ "$?" != "0" ];then 
        exit -1
    fi
    unix2dos $i
    if [ "$?" != "0" ];then 
        exit -1
    fi
done
cd ..
touch unpacked
