            title   'Hello from assembler (rasm86 with data segment)'


            cseg  
            mov     cx,ds
            mov     es,cx
            mov     cx,09h
            mov     dx,offset msg
            int     0E0h
            xor     cx,cx
            int     0E0h

            dseg    
msg         db      'Hello from assembler (rasm86 with data segment)$'
            end
