#!/bin/sh

set -e

echo Testing ...
(PATH=`pwd`/../bin:$PATH;"${MAKE:-make}" -j 1 clean hellodrc.cmd hellodra.cmd)
(PATH=`pwd`/../bin:$PATH;emu2 hellodrc.cmd)
(PATH=`pwd`/../bin:$PATH;emu2 hellodra.cmd)
