#!/bin/sh

set -e

echo INF: Checking TNYLPO ...
cd "$root"
if [ ! -d tnylpo ];then
    git clone "https://gitlab.com/gbrein/tnylpo.git"
    rm -rf tnylpo/.git
fi
if [ ! -f bin/tnylpo ];then
    ncpus="$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || getconf NPROCESSORS_ONLN 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null || printf '%s\n' 1)"
    (cd tnylpo;"${MAKE:-make}" -j"$ncpus";cp tnylpo ../bin)
fi
