#!/bin/sh

set -e

echo INF: Checking TNYLPO ...
mkdir -p "$root/archive"
if [ ! -d "$root/archive/tnylpo" ];then
    git clone "https://gitlab.com/gbrein/tnylpo.git" "$root/archive/tnylpo"
    rm -rf "$root/archive/tnylpo/.git"
fi
if [ ! -f "$root/bin/tnylpo" ];then
    ncpus="$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || getconf NPROCESSORS_ONLN 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null || printf '%s\n' 1)"
    (cd "$root/archive/tnylpo";make -j"$ncpus";cp tnylpo "$root/bin")
fi
