#!/bin/sh

set -e

echo INF: Checking DOS DR tools ...
if [ ! -f "$root/share/pcdev/linkcmd.exe" ] || [ ! -f "$root/share/pcdev/rasm86.exe" ] \
   || [ ! -f "$root/share/pcdev/linkexe.exe" ] || [ ! -f "$root/share/pcdev/lib86.exe" ]; then
    tmp="$root/share/temp-drtools"
    rm -rf "$tmp"
    mkdir -p "$tmp" "$root/share/pcdev"
    trap 'rm -rf "$tmp"' EXIT
    (cd "$tmp" && fetch_get "http://www.cpm.z80.de/download/tools86.zip" \
        && unzip -L "$ARCHIVED_FILE" && unzip -L dos86pr2.zip)
    cp "$tmp/linkcmd.exe" "$tmp/rasm86.exe" "$tmp/linkexe.exe" "$tmp/lib86.exe" \
       "$root/share/pcdev"
    chmod 644 "$root/share/pcdev"/*.*
    rm -rf "$tmp"
    trap - EXIT
fi
echo INF: Checking CP/M-80 DR tools ...
if [ ! -f "$root/share/cpm/asm86.com" ] || [ ! -f "$root/share/cpm/gencmd.com" ]; then
    tmp="$root/share/temp-drtools"
    rm -rf "$tmp"
    mkdir -p "$tmp" "$root/share/cpm"
    trap 'rm -rf "$tmp"' EXIT
    (cd "$tmp" && fetch_get "http://www.cpm.z80.de/download/mpm862sr.zip" \
        && unzip -L "$ARCHIVED_FILE")
    cp "$tmp/03/a86.cpm"    "$root/share/cpm/asm86.com"
    cp "$tmp/03/gencmd.cpm" "$root/share/cpm/gencmd.com"
    chmod 644 "$root/share/cpm/asm86.com" "$root/share/cpm/gencmd.com"
    rm -rf "$tmp"
    trap - EXIT
fi
echo INF: Checking CP/M-86 DR tools ...
if [ ! -f "$root/share/cpm/asm86.cmd" ] || [ ! -f "$root/share/cpm/gencmd.cmd" ]; then
    mkdir -p "$root/share/cpm"
    fetch_get "https://github.com/tsupplis/cpm86-kernel/raw/refs/heads/main/base/asm86.cmd" "asm86.cmd"
    cp "$ARCHIVED_FILE" "$root/share/cpm/asm86.cmd"
    fetch_get "https://github.com/tsupplis/cpm86-kernel/raw/refs/heads/main/base/gencmd.cmd" "gencmd.cmd"
    cp "$ARCHIVED_FILE" "$root/share/cpm/gencmd.cmd"
    chmod 644 "$root/share/cpm/asm86.cmd" "$root/share/cpm/gencmd.cmd"
fi
echo INF: Checking Personal Basic 86 1.2 ...
if [ ! -f "$root/share/cpm/basic.cmd" ]; then
    mkdir -p "$root/share/cpm"
    cp "$root/src/drtools/basic.cmd" "$root/share/cpm/basic.cmd"
    chmod 644 "$root/share/cpm/basic.cmd"
fi
echo INF: Checking XLT86 1.3 for CP/M-80 ...
if [ ! -f "$root/share/cpm/xlt86.com" ]; then
    tmp="$root/share/temp-drtools"
    rm -rf "$tmp"
    mkdir -p "$tmp" "$root/share/cpm"
    trap 'rm -rf "$tmp"' EXIT
    (cd "$tmp" && fetch_get "http://www.cpm.z80.de/download/xlt86.zip" \
        && unzip -L "$ARCHIVED_FILE")
    cp "$tmp/xlt86.com" "$tmp/xlt00.ovl" "$tmp/xlt01.ovl" "$root/share/cpm"
    chmod 644 "$root/share/cpm/xlt86.com" \
              "$root/share/cpm/xlt00.ovl" "$root/share/cpm/xlt01.ovl"
    rm -rf "$tmp"
    trap - EXIT
fi
