#!/bin/sh

set -e

echo INF: Checking M2CBASIC 1.4 for CP/M-86 ...
cd "$root/share"
if [ ! -f m2cbcpm/m2cbasic.cmd ]; then
    tmp="$root/archive/temp-m2cb"
    rm -rf "$tmp"
    mkdir -p "$root/share/m2cbcpm" "$tmp"
    trap 'rm -rf "$tmp"' EXIT
    cd "$tmp"
    fetch_get "http://www.cpm.z80.de/download/m2cbasic.zip"
    unzip -L "$ARCHIVED_FILE"
    cp m2cbasic.cmd m2cb1.ovr m2cb2.ovr m2cb3.ovr m2cb4.ovr m2cb5.ovr \
       m2cb6.ovr m2cb7.ovr m2cb8.ovr m2cb9.ovr "$root/share/m2cbcpm"
    cp m2cbconv.cmd m2cblib.bas m2cbrio.bas m2cbrio.rlo m2cbrio.am "$root/share/m2cbcpm"
    cp ws-fix.cmd read.me "$root/share/m2cbcpm"
    chmod 644 "$root/share/m2cbcpm"/*
    rm -rf "$tmp"
    trap - EXIT
fi
