#!/bin/sh

set -e

echo INF: Checking DR C 86 1.11 ...
cd "$root/share"
if [ ! -f drc86cpm/drc860.cmd ]; then
    tmp="$root/archive/temp-drc"
    rm -rf "$tmp"
    mkdir -p "$root/share/drc86cpm" "$tmp"
    trap 'rm -rf "$tmp"' EXIT
    cd "$tmp"
    fetch_get "http://www.cpm.z80.de/download/drc_86.zip"
    unzip -L "$ARCHIVED_FILE"
    cp v1-11/disk1/drc860.cmd v1-11/disk1/drc861.cmd \
       v1-11/disk1/drc862.cmd v1-11/disk1/drcrpp.cmd \
       v1-11/disk1/drc.err "$root/share/drc86cpm"
    cp v1-11/disk1/ctype.h v1-11/disk1/errno.h v1-11/disk1/portab.h \
       v1-11/disk1/setjmp.h v1-11/disk1/stdio.h "$root/share/drc86cpm"
    cp v1-11/disk2/clearl.l86 v1-11/disk2/clears.l86 \
       v1-11/disk2/startup.a86 "$root/share/drc86cpm"
    cp v1-11/disk3/link86.cmd "$root/share/drc86cpm"
    cp "$root/share/pcdev/linkcmd.exe" "$root/share/drc86cpm"
    chmod 644 "$root/share/drc86cpm"/*
    rm -rf "$tmp"
    trap - EXIT
fi
echo INF: Checking DR C 86 1.11 extra headers ...
cd "$root/share"
if [ ! -f drc86cpm/alloc.h ]; then
    tmp="$root/archive/temp-drc"
    rm -rf "$tmp"
    mkdir -p "$tmp"
    trap 'rm -rf "$tmp"' EXIT
    cd "$tmp"
    fetch_get "http://www.cpm.z80.de/download/drc86111.zip"
    unzip -L "$ARCHIVED_FILE"
    cp alloc.h dos.h bios.h float.h conio.h "$root/share/drc86cpm"
    cp pcbios.a86 "$root/share/drc86cpm"
    chmod 644 "$root/share/drc86cpm/alloc.h" "$root/share/drc86cpm/dos.h" "$root/share/drc86cpm/bios.h" \
              "$root/share/drc86cpm/float.h" "$root/share/drc86cpm/conio.h" "$root/share/drc86cpm/pcbios.a86"
    rm -rf "$tmp"
    trap - EXIT
fi
echo INF: Assembling DR C 86 1.11 pcbios ...
if [ ! -f "$root/share/drc86cpm/pcbios.obj" ]; then
    (cd "$root/share/drc86cpm" && "$root/bin/pcdev_rasm86" pcbios.a86 '$' nc)
fi
