#!/bin/sh

set -e

echo INF: Checking DOS DR tools ...
if [ ! -f "$root/share/pcdev/linkcmd.exe" ] || [ ! -f "$root/share/pcdev/rasm86.exe" ] \
   || [ ! -f "$root/share/pcdev/linkexe.exe" ] || [ ! -f "$root/share/pcdev/lib86.exe" ] \
   || [ ! -f "$root/share/pcdev/xref86.exe" ] || [ ! -f "$root/share/pcdev/sid86.exe" ]; then
    mkdir -p "$root/share/pcdev"
    cp "$root/src/drtools/linkcmd.exe" "$root/src/drtools/rasm86.exe" \
       "$root/src/drtools/linkexe.exe" "$root/src/drtools/lib86.exe" \
       "$root/src/drtools/sid86.exe" "$root/src/drtools/sid86.exe" \
       "$root/src/drtools/xref86.exe" "$root/share/pcdev"
    chmod 644 "$root/share/pcdev"/*.*
fi
echo INF: Checking CP/M-80 DR tools ...
if [ ! -f "$root/share/cpm/asm86.com" ] || [ ! -f "$root/share/cpm/gencmd.com" ] || \
    [ ! -f "$root/share/cpm/asm80.com" ]; then
    mkdir -p "$root/share/cpm"
    cp "$root/src/drtools/asm86.com" "$root/share/cpm/asm86.com"
    cp "$root/src/drtools/gencmd.com" "$root/share/cpm/gencmd.com"
    cp "$root/src/drtools/asm80.com" "$root/share/cpm/asm80.com"
    chmod 644 "$root/share/cpm/asm86.com" "$root/share/cpm/gencmd.com" \
        "$root/share/cpm/asm80.com"
fi
echo INF: Checking CP/M-86 DR tools ...
if [ ! -f "$root/share/cpm/asm86.cmd" ] || [ ! -f "$root/share/cpm/gencmd.cmd" ] || \
   [ ! -f "$root/share/cpm/sid86.cmd" ] || [ ! -f "$root/share/cpm/ddt86.cmd" ] || \
   [ ! -f "$root/share/cpm/pip.cmd" ]; then
    mkdir -p "$root/share/cpm"
    cp "$root/src/drtools/asm86.cmd" "$root/share/cpm/asm86.cmd"
    cp "$root/src/drtools/gencmd.cmd" "$root/share/cpm/gencmd.cmd"
    cp "$root/src/drtools/sid86.cmd" "$root/share/cpm/sid86.cmd"
    cp "$root/src/drtools/ddt86.cmd" "$root/share/cpm/ddt86.cmd"
    cp "$root/src/drtools/pip.cmd" "$root/share/cpm/pip.cmd"
    chmod 644 "$root/share/cpm/asm86.cmd" "$root/share/cpm/gencmd.cmd" \
        "$root/share/cpm/sid86.cmd" "$root/share/cpm/ddt86.cmd" "$root/share/cpm/pip.cmd"
fi
echo INF: Checking Personal Basic 86 1.2 ...
if [ ! -f "$root/share/cpm/basic.cmd" ]; then
    mkdir -p "$root/share/cpm"
    cp "$root/src/drtools/basic.cmd" "$root/share/cpm/basic.cmd"
    chmod 644 "$root/share/cpm/basic.cmd"
fi
echo INF: Checking XLT86 1.3 for CP/M-80 ...
if [ ! -f "$root/share/cpm/xlt86.com" ]; then
    mkdir -p "$root/share/cpm"
    cp "$root/src/drpackages/xlt86"/* "$root/share/cpm"
    chmod 644 "$root/share/cpm/xlt86.com" \
              "$root/share/cpm/xlt00.ovl" "$root/share/cpm/xlt01.ovl"
fi
