#!/bin/sh

set -e

echo INF: Checking Pascal MT+ 3.3 for CP/M-86 ...
cd "$root/share"
if [ ! -f drpmtcpm/mt-86.cmd ]; then
    mkdir -p "$root/share/drpmtcpm"
    cp "$root/src/drpackages/drpmtcpm"/* "$root/share/drpmtcpm"
    chmod 644 "$root/share/drpmtcpm"/*
fi
