#!/bin/sh

set -e

echo INF: Checking Microsoft tools ...
if [ ! -f "$root/share/pcdev/masm.exe" ] || [ ! -f "$root/share/pcdev/exe2bin.exe" ] || \
   [ ! -f "$root/share/pcdev/link3.exe" ] || [ ! -f "$root/share/pcdev/masm11.exe" ] || \
   [ ! -f "$root/share/pcdev/link5.exe" ] || [ ! -f "$root/share/pcdev/gwbasic.exe" ]; then
    mkdir -p "$root/share/pcdev"
    cp "$root/src/mstools/link3.exe" "$root/share/pcdev"
    cp "$root/src/mstools/link5.exe" "$root/share/pcdev"
    cp "$root/src/mstools/masm.exe" "$root/share/pcdev"
    cp "$root/src/mstools/masm11.exe" "$root/share/pcdev"
    cp "$root/src/mstools/exe2bin.exe" "$root/share/pcdev"
    cp "$root/src/mstools/gwbasic.exe" "$root/share/pcdev"
fi
if [ ! -f "$root/share/pcdev/asm.com" ] || [ ! -f "$root/share/pcdev/hex2bin.com" ] || \
   [ ! -f "$root/share/pcdev/trans.com" ]; then
    mkdir -p "$root/share/pcdev"
    cp "$root/src/mstools/asm.com" "$root/share/pcdev"
    cp "$root/src/mstools/hex2bin.com" "$root/share/pcdev"
    cp "$root/src/mstools/trans.com" "$root/share/pcdev"
fi
if [ ! -f "$root/share/cpm/mbasic86.cmd" ]; then
    mkdir -p "$root/share/cpm"
    cp "$root/src/mstools/mbas550.cmd" "$root/share/cpm/mbasic86.cmd"
fi
if [ ! -f "$root/share/cpm/mbasic80.com" ]; then
    mkdir -p "$root/share/cpm"
    cp "$root/src/mstools/mbasic80.com" "$root/share/cpm/mbasic80.com"
fi
if [ ! -f "$root/share/cpm/obasic.com" ]; then
    mkdir -p "$root/share/cpm"
    cp "$root/src/mstools/obasic.com" "$root/share/cpm/obasic.com"
fi
if [ ! -f "$root/share/pcdev/debug.com" ]; then
    mkdir -p "$root/share/pcdev"
    cp "$root/src/mstools/debug.com" "$root/share/pcdev"
fi
if [ ! -f "$root/share/pcdev/mbasic86.exe" ]; then
    mkdir -p "$root/share/pcdev"
    cp "$root/src/mstools/mbas550.exe" "$root/share/pcdev/mbasic86.exe"
fi
