#!/bin/sh

set -e

echo INF: Checking Aztec 3.4 tools ...
if [ ! -d "$root/share/aztec34/bin" ] || [ ! -f "$root/share/emu/cpm86.exe" ]; then
    fetch_get "https://www.aztecmuseum.ca/az8634b.zip"
    tmp="$root/share/temp-aztec34"
    rm -rf "$tmp"
    mkdir -p "$tmp"
    trap 'rm -rf "$tmp"' EXIT
    (cd "$tmp" && unzip -L "$ARCHIVED_FILE")
    mkdir -p "$root/share/aztec34/src"
    mkdir -p "$root/share/emu"
    mkdir -p "$root/share/aztec42/src"
    cp -R "$tmp/az8634b/bin"        "$root/share/aztec34/bin"
    cp -R "$tmp/az8634b/lib"        "$root/share/aztec34/lib"
    cp    "$tmp/az8634b/emu/cpm.exe" "$root/share/emu/cpm86.exe"
    cp -R "$tmp/az8634b/obj/."      "$root/share/aztec34/lib"
    cp -R "$tmp/az8634b/src"        "$root/share/aztec34/src"
    cp    "$tmp/az8634b/src/dos11.arc" "$root/share/aztec42/src"
    cp    "$tmp/az8634b/src/cpm86.arc" "$root/share/aztec42/src"
    cp -R "$tmp/az8634b/include"    "$root/share/aztec34/include"
    rm -rf "$tmp"
    trap - EXIT
fi

echo INF: Patching the Aztec 3.4 preprocessor ...
ccb34="$root/share/aztec34/bin/ccb.exe"
cc34="$root/share/aztec34/bin/cc.exe"
if [ -f "$cc34" ] && [ ! -f "$cc34.bak" ] && \
   [ -f "$ccb34" ] && [ ! -f "$ccb34.bak" ]; then
    (cd "$root/share" && sh "$root/src/patch/patch_aztec_cpp")
fi
