#!/bin/sh

set -e

echo INF: Unpacking Aztec 4.2 ...
if [ ! -f "$root/share/aztec42/unpacked" ]; then
    (cd "$root/share/aztec42" && "$root/src/aztec42-patch/unpack")
fi
echo INF: Patching Aztec 4.2 ...
if [ ! -f "$root/share/aztec42/patched" ]; then
    set -x
    (cd "$root/share/aztec42" && tar zxvf "$root/src/aztec42-patch/patches.tar.gz")
    (cd "$root/share/aztec42" && "$root/src/aztec42-patch/apply_patches")
    (cd "$root/share/aztec42" && sed 's|make |$(MAKE) |' src/makefile > src/makefile.sed && mv -f src/makefile.sed src/makefile || true)
    (cd "$root/share/aztec42" && sed 's|make |"${MAKE:-make}" |' src/build > src/build.sed && mv -f src/build.sed src/build || true)
fi
echo INF: Building Aztec 4.2 ...
if [ ! -f "$root/share/aztec42/built" ]; then
    chmod 755 "$root/share/aztec42/src/build"
    (cd "$root/share/aztec42/src" && PATH="$root/bin:$PATH" ./build)
    rm -rf "$root/share/aztec42/lib"/*
    mv "$root/share/aztec42/src/libs"/* "$root/share/aztec42/lib"
    mv "$root/share/aztec42/src/screen"/*.lib "$root/share/aztec42/lib"
    touch "$root/share/aztec42/built"
fi
if [ ! -f "$root/share/aztec42/tools_built" ]; then
    (cd "$root/src/tools" && "${MAKE:-make}")
    touch "$root/share/aztec42/tools_built"
fi
