#!/bin/sh

set -e

echo INF: Checking lzexe for DOS ...
cd "$root/share"
if [ ! -f lzexe/lzexe.exe ]; then
    tmp="$root/archive/temp-debug"
    rm -rf "$tmp"
    mkdir -p "$root/share/pcdev" "$tmp"
    trap 'cd .. && rm -rf "$tmp"' EXIT
    cd "$tmp"
    fetch_get "https://pushbx.org/ecm/download/msdebug.zip"
    unzip -L "$ARCHIVED_FILE"
    cp -f debug.com "$root/share/pcdev/edebug.com"
    chmod 644 "$root/share/pcdev/edebug.com"
    fetch_get "https://pushbx.org/ecm/download/ldebug.zip"
    unzip -L "$ARCHIVED_FILE"
    cp -f debug.com "$root/share/pcdev/ldebug.exe"
    chmod 644 "$root/share/pcdev/ldebug.exe"
    cd .. && rm -rf "$tmp"
    trap - EXIT
fi
