#!/bin/sh

set -e

echo INF: Checking PL/I-86 1.0 for CP/M-86 ...
cd "$root/share"
if [ ! -f plicpm/pli.cmd ]; then
    tmp="$root/archive/temp-pli"
    rm -rf "$tmp"
    mkdir -p "$root/share/plicpm" "$tmp"
    trap 'rm -rf "$tmp"' EXIT
    cd "$tmp"
    fetch_get "http://www.cpm.z80.de/download/pli86.zip"
    unzip -L "$ARCHIVED_FILE"
    unzip -L pli86-1.zip
    cp pli.cmd pli0.ovr pli1.ovr pli2.ovr "$root/share/plicpm"
    cp link86.cmd lib86.cmd xref86.cmd "$root/share/plicpm"
    cp plilib.l86 "$root/share/plicpm"
    cp dio86.dcl diomod.dcl fcb.dcl record.dcl matsize.lib "$root/share/plicpm"
    cp cpmdio.a86 div2.a86 fdiv2.a86 "$root/share/plicpm"
    cp "$root/share/pcdev/linkcmd.exe" "$root/share/plicpm"
    chmod 644 "$root/share/plicpm"/*
    rm -rf "$tmp"
    trap - EXIT
fi
