#!/bin/sh

set -e

echo INF: Checking Microsoft tools ...
if [ ! -f "$root/share/pcdev/masm.exe" ] || [ ! -f "$root/share/pcdev/exe2bin.exe" ] || [ ! -f "$root/share/pcdev/link.exe" ]; then
    mkdir -p "$root/share/pcdev"
    cp "$root/src/mstools"/*.exe "$root/share/pcdev"
    chmod 644 "$root/share/pcdev"/*.*
fi
if [ ! -f "$root/share/pcdev/asm.com" ] || [ ! -f "$root/share/pcdev/hex2bin.com" ]; then
    mkdir -p "$root/share/pcdev"
    cp "$root/src/mstools"/*.com "$root/share/pcdev"
    chmod 644 "$root/share/pcdev"/*.*
fi
if [ ! -f "$root/share/cpm/mbasic86.cmd" ]; then
    mkdir -p "$root/share/cpm"
    cp "$root/src/mstools/mbasic86.cmd" "$root/share/cpm"
    chmod 644 "$root/share/cpm/mbasic86.cmd"
fi
if [ ! -f "$root/share/pcdev/mbasic86.com" ]; then
    mkdir -p "$root/share/pcdev"
    cp "$root/src/mstools/mbasic86.com" "$root/share/pcdev"
    chmod 644 "$root/share/pcdev/mbasic86.com"
fi
