#!/bin/sh

set -e

echo INF: Checking PL/M-86 3.30 tools ...
cd "$root/share"
if [ ! -f intel/plm86.exe -o ! -f intel/asm86.exe -o ! -f intel/link.exe \
    -o ! -f intel/lib86.exe -o ! -f intel/loc86.exe ]; then
    mkdir -p "$root/share/intel"
    cp "$root/src/inteltools"/* "$root/share/intel"
    chmod 644 "$root/share/intel"/*
fi
