#!/bin/sh

set -e

echo INF: Checking Pascal MT+ 3.3 for CP/M-86 ...
cd "$root/share"
if [ ! -f drpmtcpm/mt-86.cmd ]; then
    rm -rf "$root/share/temp-tools"
    mkdir -p "$root/share/drpmtcpm"
    mkdir -p "$root/share/temp-tools"
    cd "$root/share/temp-tools"
    fetch_get "http://www.cpm.z80.de/download/mt8633cp.zip"
    unzip -L "$ARCHIVED_FILE"
    cp mt-86.cmd mt-86.000 mt-86.001 mt-86.002 mt-86.003 mt-86.004 mt-86.005 ../drpmtcpm
    cp linkmt.cmd linkmt.001 linkmt.002 ../drpmtcpm
    cp asmt86.cmd asmt86.001 asmt86.002 asmt86.003 asmt86.004 ../drpmtcpm
    cp libmt.cmd mt2int.cmd strip.cmd sz.cmd nm.cmd dis86.cmd ../drpmtcpm
    cp paslib.r86 fpreals.r86 bcdreals.r86 87reals.r86 87trans.r86 ../drpmtcpm
    cp fullheap.r86 debugger.r86 randomio.r86 trancend.r86 ../drpmtcpm
    cp halt.r86 pasint.r86 ioerrors.r86 iomod4.r86 ovlmgr4.r86 ../drpmtcpm
    cp mterrs.txt asmers.txt fibdef.lib ../drpmtcpm
    chmod 644 ../drpmtcpm/*
    cd "$root/share"
    rm -rf "$root/share/temp-tools"
fi
