#!/bin/sh

set -e

echo INF: Checking PKLITE ...
if [ ! -d "$root/archive/pkstuff" ]; then
    mkdir -p "$root/archive/pkstuff"
    cd "$root/archive/pkstuff"
    curl -o "$root/archive/pkstuff/pklite1.exe" https://github.com/johnsonjh/pkstuff/raw/refs/heads/master/pklite/1.50/unpacked/pklite.exe 
    #curl -o "$root/archive/pkstuff/pklite2.exe" https://github.com/johnsonjh/pkstuff/raw/refs/heads/master/pklite/2.01/unpacked/pklite.exe 
fi
if [ ! -f "$root/share/pcdev/pklite1.exe" ] || [ ! -f "$root/share/pcdev/pklite2.exe" ]; then
    mkdir -p "$root/share/pcdev"
    cp -f "$root/archive/pkstuff/pklite1.exe" "$root/share/pcdev/pklite1.exe"
    #cp -f "$root/archive/pkstuff/pklite2.exe" "$root/share/pcdev/pklite2.exe"
fi
