#!/bin/sh

set -e

echo INF: Checking Pascal MT+ 3.3 for CP/M-86 ...
cd "$root/share"
if [ ! -f drpmtcpm/mt-86.cmd ]; then
    tmp="$root/archive/temp-drpmt"
    rm -rf "$tmp"
    mkdir -p "$root/share/drpmtcpm" "$tmp"
    trap 'rm -rf "$tmp"' EXIT
    cd "$tmp"
    fetch_get "http://www.cpm.z80.de/download/mt8633cp.zip"
    unzip -L "$ARCHIVED_FILE"
    cp mt-86.cmd mt-86.000 mt-86.001 mt-86.002 mt-86.003 mt-86.004 mt-86.005 "$root/share/drpmtcpm"
    cp linkmt.cmd linkmt.001 linkmt.002 "$root/share/drpmtcpm"
    cp asmt86.cmd asmt86.001 asmt86.002 asmt86.003 asmt86.004 "$root/share/drpmtcpm"
    cp libmt.cmd mt2int.cmd strip.cmd sz.cmd nm.cmd dis86.cmd "$root/share/drpmtcpm"
    cp paslib.r86 fpreals.r86 bcdreals.r86 87reals.r86 87trans.r86 "$root/share/drpmtcpm"
    cp fullheap.r86 debugger.r86 randomio.r86 trancend.r86 "$root/share/drpmtcpm"
    cp halt.r86 pasint.r86 ioerrors.r86 iomod4.r86 ovlmgr4.r86 "$root/share/drpmtcpm"
    cp mterrs.txt asmers.txt fibdef.lib "$root/share/drpmtcpm"
    chmod 644 "$root/share/drpmtcpm"/*
    rm -rf "$tmp"
    trap - EXIT
fi
