#!/bin/sh

set -e

echo INF: Checking Microsoft Basic 5.21 for CP/M-80 ...
if [ ! -f "$root/share/cpm/mbasic.com" ]; then
    fetch_get "http://cpmarchives.classiccmp.org/cpm/mirrors/www.retroarchive.org/cpm/lang/Mbasic.com"
    cp -f "$root/archive/Mbasic.com" "$root/share/cpm/mbasic.com"
    chmod 644 "$root/share/cpm/mbasic.com"
fi
