#!/bin/sh
echo INF: Checking CP/M DR tools ...
cd "$root/share"
if [ ! -f cpm/asm86.com -o ! -f cpm/gencmd.com ]; then
    rm -rf "$root/share/temp-tools"
    mkdir -p "$root/share/cpm"
    mkdir -p "$root/share/temp-tools"
    cd "$root/share/temp-tools"
    fetch_get "http://www.cpm.z80.de/download/mpm862sr.zip"
    unzip -L "$ARCHIVED_FILE"
    cp 03/a86.cpm ../cpm/asm86.com
    cp 03/gencmd.cpm ../cpm/gencmd.com
    chmod 644 ../cpm/*.*
    rm -rf "$root/share/temp-tools"
fi
echo INF: Checking CP/M-86 DR tools ...
cd "$root/share"
if [ ! -f cpm/asm86.cmd -o ! -f cpm/gencmd.cmd ]; then
    mkdir -p "$root/share/cpm"
    fetch_get "https://github.com/tsupplis/cpm86-kernel/raw/refs/heads/main/base/asm86.cmd" "asm86.cmd"
    cp "$ARCHIVED_FILE" "$root/share/cpm/asm86.cmd"
    fetch_get "https://github.com/tsupplis/cpm86-kernel/raw/refs/heads/main/base/gencmd.cmd" "gencmd.cmd"
    cp "$ARCHIVED_FILE" "$root/share/cpm/gencmd.cmd"
    chmod 644 "$root/share/cpm/asm86.cmd" "$root/share/cpm/gencmd.cmd"
fi
echo INF: Checking DOS DR tools ...
cd "$root/share"
if [ ! -f pcdev/linkcmd.exe -o ! -f pcdev/rasm86.exe -o ! -f pcdev/linkexe.exe \
   -o ! -f pcdev/lib86.exe ]; then
    rm -rf "$root/share/temp-tools"
    mkdir -p "$root/share/pcdev"
    mkdir -p "$root/share/temp-tools"
    cd "$root/share/temp-tools"
    fetch_get "http://www.cpm.z80.de/download/tools86.zip"
    unzip -L "$ARCHIVED_FILE"
    unzip -L dos86pr2.zip
    cp linkcmd.exe rasm86.exe ../pcdev
    cp linkexe.exe ../pcdev
    cp lib86.exe ../pcdev
    chmod 644 ../pcdev/*.*
    rm -rf "$root/share/temp-tools"
fi
