#!/bin/sh
echo INF: Checking CP/M DR tools ...
cd "$root/share"
if [ ! -f cpm/asm86.com -o ! -f cpm/gencmd.com ]; then
    rm -rf "$root/share/temp-tools"
    mkdir -p "$root/share/cpm"
    mkdir -p "$root/share/temp-tools"
    cd "$root/share/temp-tools"
    fetch_get "http://www.cpm.z80.de/download/mpm862sr.zip"
    unzip -L "$ARCHIVED_FILE"
    cp 03/a86.cpm ../cpm/asm86.com
    cp 03/gencmd.cpm ../cpm/gencmd.com
    chmod 644 ../cpm/*.*
    rm -rf "$root/share/temp-tools"
fi
echo INF: Checking CP/M-86 DR tools ...
cd "$root/share"
if [ ! -f cpm/asm86.cmd -o ! -f cpm/gencmd.cmd ]; then
    mkdir -p "$root/share/cpm"
    fetch_get "https://github.com/tsupplis/cpm86-kernel/raw/refs/heads/main/base/asm86.cmd" "asm86.cmd"
    cp "$ARCHIVED_FILE" "$root/share/cpm/asm86.cmd"
    fetch_get "https://github.com/tsupplis/cpm86-kernel/raw/refs/heads/main/base/gencmd.cmd" "gencmd.cmd"
    cp "$ARCHIVED_FILE" "$root/share/cpm/gencmd.cmd"
    chmod 644 "$root/share/cpm/asm86.cmd" "$root/share/cpm/gencmd.cmd"
fi
echo INF: Checking Personal Basic 86 1.0 ...
cd "$root/share"
if [ ! -f cpm/basic.cmd ]; then
    rm -rf "$root/share/temp-tools"
    mkdir -p "$root/share/cpm"
    mkdir -p "$root/share/temp-tools"
    cd "$root/share/temp-tools"
    fetch_get "http://www.cpm.z80.de/download/pbasic86.zip"
    unzip -L "$ARCHIVED_FILE"
    cp basic.cmd ../cpm
    chmod 644 ../cpm/basic.cmd
    rm -rf "$root/share/temp-tools"
fi
echo INF: Checking DR C 86 1.11 ...
cd "$root/share"
if [ ! -f drc86cpm/drc860.cmd ]; then
    rm -rf "$root/share/temp-tools"
    mkdir -p "$root/share/drc86cpm"
    mkdir -p "$root/share/temp-tools"
    cd "$root/share/temp-tools"
    fetch_get "http://www.cpm.z80.de/download/drc_86.zip"
    unzip -L "$ARCHIVED_FILE"
    cp v1-11/disk1/drc860.cmd v1-11/disk1/drc861.cmd \
       v1-11/disk1/drc862.cmd v1-11/disk1/drcrpp.cmd \
       v1-11/disk1/drc.err ../drc86cpm
    cp v1-11/disk1/ctype.h v1-11/disk1/errno.h v1-11/disk1/portab.h \
       v1-11/disk1/setjmp.h v1-11/disk1/stdio.h ../drc86cpm
    cp v1-11/disk2/clearl.l86 v1-11/disk2/clears.l86 \
       v1-11/disk2/startup.a86 ../drc86cpm
    cp v1-11/disk3/link86.cmd ../drc86cpm
    chmod 644 ../drc86cpm/*
    rm -rf "$root/share/temp-tools"
fi
echo INF: Checking DR C 86 1.11 extra headers ...
cd "$root/share"
if [ ! -f drc86cpm/alloc.h ]; then
    rm -rf "$root/share/temp-tools"
    mkdir -p "$root/share/temp-tools"
    cd "$root/share/temp-tools"
    fetch_get "http://www.cpm.z80.de/download/drc86111.zip"
    unzip -L "$ARCHIVED_FILE"
    cp alloc.h dos.h bios.h float.h conio.h ../drc86cpm
    cp pcbios.a86 ../drc86cpm
    chmod 644 ../drc86cpm/alloc.h ../drc86cpm/dos.h ../drc86cpm/bios.h \
              ../drc86cpm/float.h ../drc86cpm/conio.h ../drc86cpm/pcbios.a86
    rm -rf "$root/share/temp-tools"
fi
echo INF: Checking DOS DR tools ...
cd "$root/share"
if [ ! -f pcdev/linkcmd.exe -o ! -f pcdev/rasm86.exe -o ! -f pcdev/linkexe.exe \
   -o ! -f pcdev/lib86.exe ]; then
    rm -rf "$root/share/temp-tools"
    mkdir -p "$root/share/pcdev"
    mkdir -p "$root/share/temp-tools"
    cd "$root/share/temp-tools"
    fetch_get "http://www.cpm.z80.de/download/tools86.zip"
    unzip -L "$ARCHIVED_FILE"
    unzip -L dos86pr2.zip
    cp linkcmd.exe rasm86.exe ../pcdev
    cp linkexe.exe ../pcdev
    cp lib86.exe ../pcdev
    chmod 644 ../pcdev/*.*
    rm -rf "$root/share/temp-tools"
fi
echo INF: Assembling DR C 86 1.11 pcbios ...
if [ ! -f "$root/share/drc86cpm/pcbios.obj" ]; then
    cd "$root/share/drc86cpm"
    "$root/bin/pcdev_rasm86" pcbios.a86 '$' nc
    cd "$root/share"
fi
