#!/bin/sh

set -e

echo INF: Checking TNYLPO ...
mkdir -p "$root/archive"
if [ ! -d "$root/archive/tnylpo" ];then
    git clone "https://gitlab.com/gbrein/tnylpo.git" "$root/archive/tnylpo"
    rm -rf "$root/archive/tnylpo/.git"
fi
if [ ! -f "$root/bin/tnylpo" ];then
    ncpus="$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || getconf NPROCESSORS_ONLN 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null || printf '%s\n' 1)"
    # Best effort to apply the `-X` patch to upstream tnylpo; if it fails, it's not an issue.
    XPATCH="https://raw.githubusercontent.com/johnsonjh/lzpack/refs/heads/master/tnylpo.diff"
    (cd "$root/archive/tnylpo" && { { curl -fsSL "${XPATCH:?}" | "${PATCH:?}" --dry-run -p1 ; } && { curl -fsSL "${XPATCH:?}" | "${PATCH:?}" -p1 ; }; }) || :
    (cd "$root/archive/tnylpo";env CC="${CC:-cc}" sh ./build.sh all;cp tnylpo "$root/bin" && cp tnylpo-convert "$root/bin")
fi
