#!/bin/sh

set -e

echo INF: Checking NASM ...
mkdir -p "$root/archive"
if [ ! -d "$root/archive/nasm" ];then
    devurl="https://nasm.us/pub/nasm/snapshots/"
    cururl="$(curl -s "${devurl:?}" |
        sed -n 's/.*href="\([^"]*\)".*/\1/p' | tr -cd '0-9\n' |
        sort -nr | head -1)"
    curfil="$(curl -s "${devurl:?}${cururl:?}/" |
        sed -n "s/.*href=\"\(nasm-[^\"]*${cururl}\.tar\.gz\)\".*/\1/p" |
        sort -nr | head -1)"
    curdir=${curfil%.tar.gz}
    fetch_get "https://nasm.us/pub/nasm/snapshots/${cururl:?}/${curfil:?}"
    "$(command -v gtar 2> /dev/null || printf '%s\n' tar)" zxf "$ARCHIVED_FILE" -C "$root/archive"
    mv -f "$root/archive/${curdir:?}" "$root/archive/nasm"
fi
if [ ! -f "$root/bin/nasm" ];then
    ncpus="$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || getconf NPROCESSORS_ONLN 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null || printf '%s\n' 1)"
    (cd "$root/archive/nasm";./configure)
    # For illumos systems, we unconditionally inject '#include <endian.h>' into config/config.h
    test "$(uname -o 2> /dev/null || true)" = "illumos" && {
	(cd "$root/archive/nasm" && printf '\n%s\n' '#include <endian.h>' >> config/config.h)
    } || true
    (cd "$root/archive/nasm";"${MAKE:-make}" -j "$ncpus" ${EXTRA_FLAG:-};cp nasm "$root/bin")
fi
