#!/bin/sh

set -e

echo INF: Checking mlbr ...
mkdir -p "$root/archive"
if [ ! -d "$root/archive/mlbr" ];then
    git clone "https://github.com/ogdenpm/mlbr" "$root/archive/mlbr"
    rm -rf "$root/archive/mlbr/.git"
    mv -f "$root/archive/mlbr/mlbr/mlbr.h" "$root/archive/mlbr/mlbr/mlbr.h.org"
    # this line needs to be removed when upstream with APPLE available
    sed -e 's/__HAIKU__/__HAIKU__) || defined(__APPLE__/' "$root/archive/mlbr/mlbr/mlbr.h.org" > "$root/archive/mlbr/mlbr/mlbr.h"
    mv -f "$root/archive/mlbr/Linux/Makefile" "$root/archive/mlbr/Linux/Makefile.org"
    sed 's|SHELL=bash|SHELL=/bin/sh|' "$root/archive/mlbr/Linux/Makefile.org" > "$root/archive/mlbr/Linux/Makefile"
fi
if [ ! -f "$root/bin/mlbr" ];then
    ncpus="$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || getconf NPROCESSORS_ONLN 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null || printf '%s\n' 1)"
    (cd "$root/archive/mlbr/Linux";"${MAKE:-make}" -j"$ncpus" CC="${CC:-cc}" LINKER="${CC:-cc}";cp "$root/archive/mlbr/Linux/Install/mlbr" "$root/bin")
fi
